<?php

/**
 * @category   OpenCart
 * @package    SEO Tags Generator
 * @copyright  © Serge Tkach, 2017, https://opencartforum.com/profile/717101-sergetkach/
 */

// Heading
$_['heading_title'] = 'SEO Tags Generator';


// Text
$_['text_extension']   = 'Modules';
$_['text_success']     = 'SEO Tags Generator settings modified';
$_['text_edit']        = 'Edit SEO Tags Generator';
$_['text_available_vars'] = 'Available Vars';

$_['text_author']        = 'Author';  // v1.3
$_['text_author_support'] = 'Support';  // v1.3


// Fieldsets
$_['fieldset_setting'] = 'Setting'; // v1.3
$_['fieldset_formula_common'] = 'The general formula'; // v1.3
$_['fieldset_formula_specific'] = 'Formulas for specific categories'; // v1.3


// Tab
$_['tab_category']     = 'Categories';
$_['tab_product']      = 'Products';
$_['tab_manufacturer'] = 'Manufacturers';


// Entry
$_['entry_licence']    = 'Licence Code';
$_['entry_temp_licence'] = 'Temporal Licence Code';
$_['entry_temp_licence_tooltip'] = 'A temporary license allows you to start working with the module before you get a real licence code';

$_['entry_status']     = 'Module Status';

$_['entry_status_category_title']  = 'Generate category Title in any case';
$_['entry_status_category_title_tooltip'] = 'The category tag Title will be generated by category title formula, even if it will be completed in the admin';

$_['entry_status_category_description']  = 'Generate category Description in any case';
$_['entry_status_category_description_tooltip'] = 'The category tag Description will be generated by category description formula, even if it will be completed in the admin';

$_['entry_status_product_h1']  = 'Генерировать H1 товара принудительно';
$_['entry_status_product_h1_tooltip'] = 'Название товара на сайте будет сгенерировано по формуле H1 для товаров, даже если будет заполнено в админке';

$_['entry_inheritance'] = 'Наследование формул от родительской категории к дочерней';
$_['entry_inheritance_tooltip'] = 'Если для родительской категории MP3-плееры указана специфическая (недефолтная) формула, то как поступать, если для ее дочерней категории MP3-плееры Transcend формула не указана?<br> Считать ли, что раз эта категория дочерняя, то использовать формулу родителя?';


$_['entry_category_title'] = 'Тег Title';
$_['entry_category_description'] = 'Тег Description';
$_['entry_category_keyword'] = 'Тег Keywords'; // v1.4

$_['entry_product_h1'] = 'Тег H1';
$_['entry_product_title'] = 'Тег Title';
$_['entry_product_description'] = 'Тег Description';
$_['entry_product_keyword'] = 'Тег Keywords'; // v1.4

$_['entry_manufacturer_title'] = 'Тег Title';
$_['entry_manufacturer_description'] = 'Тег Description';
$_['entry_manufacturer_keyword'] = 'Тег Keywords'; // v1.4


$_['entry_category'] = 'Использовать данную формулу в категории:'; // v1.3
$_['help_category'] = '(Автозаполнение)'; // v1.3

// Для админки категорий

$_['fieldset_seo_tags_generator'] = 'Склонение названия категории (для модуля SEO Tags Generator)'; // v1.6
$_['entry_category_name_plural_nominative']   = 'Полное название категории (в мн.ч. им.пад):';
$_['entry_category_name_plural_genitive']     = 'Название категории в мн.ч. род.пад:';
$_['entry_category_name_singular_nominative'] = 'Определяющее слово товара (Название категории в ед.ч. им.пад):';

$_['entry_category_meta_stg_no_auto']   	    = 'Использовать вручную вписанные мета-теги для данной категории';
$_['entry_category_meta_stg_no_auto_help']   = 'Мета-теги генерируются по формуле в момент создания страницы. Отмеченная галочка означает, что мета-теги данной категории будут браться из базы данных и будут соответствовать тому, что сохранено в админке.';
$_['text_category_explain_stg_no_auto'] = 'Модуль <b>SEO Tags Generator</b> генрирует <i>title</i>, <i>мета-тег description</i>, <i>мета-тег keywords</i>'; // v1.6

$_['tab_seo_tags_generator'] = 'SEO Формулы'; // v1.6
$_['tab_seo_tags_generator_info'] = '<i class="fa fa-info-circle"></i> Внимание!<br>Используйте данную вкладку только в тех случаях:<br>'
  . '- если Вы хотите задать для отдельно взятой категории специфические формулы генерации мета-тегов<br>'
  . '- если Вы хотите задать отдельные форумлы для всех товаров данной категории'; // v1.6

$_['tab_category_setting'] = 'Настройки категории'; // v1.6
$_['entry_category_setting_inheritance'] = 'Наследование формул в дочерних категориях, если те будут пусты'; // v1.6
$_['text_inheritance_yes'] = 'Наследовать'; // v1.6
$_['text_inheritance_no']  = 'Не наследовать'; // v1.6

$_['entry_category_setting_inheritance_copy'] = 'Скопировать данные формулы в дочерние подкатегории, чтобы в дальнейшем слегка подправить их'; // v1.6
$_['text_inheritance_copy_yes']  = 'Да'; // v1.6
$_['text_inheritance_copy_warning']  = 'Будьте осторожны!<br>'
  . 'Вы уже копировали эти формулы. И, возможно, там внесены изменения, которые не стоит перезаписывать'; // v1.6

$_['entry_category_setting_copy_to_others'] = 'Скопировать данные формулы в другие категории сайта'; // v1.6
$_['text_copy_to_others_yes']  = 'Да'; // v1.6
$_['text_copy_to_others_warning']  = 'Будьте осторожны!<br>'
  . 'Вы уже копировали эти формулы. И, возможно, там внесены изменения, которые не стоит перезаписывать'; // v1.6

$_['entry_categories'] = 'Выберите категории'; // v1.6
$_['text_select_all'] = 'Выбрать все'; // v1.6
$_['text_unselect_all'] = 'Снять выбор со всех'; // v1.6


// Для админки товара

$_['entry_product_meta_stg_no_auto']   	    = 'Использовать вручную вписанные мета-теги для данного товара';
$_['entry_product_meta_stg_no_auto_help']   = 'Мета-теги генерируются по формуле в момент создания страницы. Отмеченная галочка означает, что мета-теги данного товара будут браться из базы данных и будут соответствовать тому, что сохранено в админке.';
$_['text_product_explain_stg_no_auto'] = 'Модуль <b>SEO Tags Generator</b> генрирует <i>title</i>, <i>мета-тег description</i>, <i>мета-тег keywords</i> и <i>h1</i> для товара. <span style="color: red; ">Поле "Теги товара" НЕ генерируется</span>. <br><br>Галочка находится здесь потому что, именно здесь заканчивается разделение языковых версий'; // v1.6

$_['entry_model_synonym']   = 'Синоним модели'; 


//button
$_['button_save'] = 'Сохранить';
$_['button_cancel'] = 'Отмена';


// success
$_['success'] = 'Настройки модуля обновлены';


// warning
$_['warning_licence'] = 'Активирована временная лицензия на [x] дней! Для получения постоянной лицензии, обратитесь к авторму модуля по адресу <b>sergheitkach@gmail.com</b>!';


// Error
$_['error_permission'] = 'У вас нет прав для управления этим модулем!';
$_['error_warning'] = 'Ошибка! Настройки не сохранены. Исправьте указанные в форме ошибки и попробуйте сохранить снова! ';

$_['error_licence'] = 'Input licence code!';
$_['error_licence_empty'] = 'Input licence code!';
$_['error_licence_not_valid'] = 'Licence code is not valid!';


// Temp licence
$_['button_get_temp_licence'] = 'Get temporal licence';
$_['success_get_temp_licence'] = 'The temporary license is received! To continue refresh the page!';
$_['error_get_temp_licence'] = 'Could not get a temporary license! Try to get it again later!';

$_['error_get_temp_licence_server_off'] = 'The server for obtaining the license was not found! Contact the author of the module!';
$_['error_get_temp_licence_waiting'] = 'The response time from the server exceeded 5 seconds and was reset. Try again later!';
$_['error_get_temp_licence_404'] = 'License receipt page not found! Contact the author of the module!';
$_['error_get_temp_licence_expired'] = 'Temporal Licence code expired!';

$_['error_valid_temp_licence'] = 'Invalid temporary license!';